// User agents turned away with a 403 before any route runs (see server.ts).
// Same list as web/public/robots.txt, which names every one of these and
// asks them not to crawl; this is for the ones that don't ask first.
//
// From https://github.com/ai-robots-txt/ai.robots.txt, minus:
//   - facebookexternalhit and plain Applebot, which aren't AI crawlers
//     (link previews when the site is shared; Apple search),
//   - names too generic to match as a substring of a user agent without
//     also catching real browsers or tools ("Code", "Spider", "Cursor",
//     "Operator"...) -- those stay in robots.txt only,
//   - tokens already covered by a shorter one ("iaskspider/2.0").
// Matched case-insensitively, anywhere in the user agent.
const AI_BOT_TOKENS = [
  'AddSearchBot',
  'AgentDataBot',
  'AgentTimes',
  'AI2Bot',
  'aiHitBot',
  'AIWebIndex',
  'amazon-kendra',
  'amazon-QBusiness',
  'Amazonbot',
  'AmazonBuyForMe',
  'Amzn-SearchBot',
  'Amzn-User',
  'anthropic-ai',
  'ApifyBot',
  'ApifyWebsiteContentCrawler',
  'Applebot-Extended',
  'Aranet-SearchBot',
  'atlassian-bot',
  'Awario',
  'AzureAI-SearchBot',
  'bedrockbot',
  'bigsur.ai',
  'BixelBot',
  'Bravebot',
  'Brightbot',
  'BuddyBot',
  'Bytespider',
  'CCBot',
  'Channel3Bot',
  'ChatGLM-Spider',
  'ChatGPT Agent',
  'ChatGPT-User',
  'Claude-Code',
  'Claude-SearchBot',
  'Claude-User',
  'Claude-Web',
  'ClaudeBot',
  'Cloudflare-AutoRAG',
  'CloudflareBrowserRenderingCrawler',
  'CloudVertexBot',
  'cohere-ai',
  'cohere-training-data-crawler',
  'Cotoyogi',
  'CragCrawler',
  'Crawl4AI',
  'Datenbank Crawler',
  'DeepSeekBot',
  'Diffbot',
  'DoubaoBot',
  'DuckAssistBot',
  'EchoboxBot',
  'ERNIEBot',
  'ExaBot',
  'ExaSearchBot',
  'FacebookBot',
  'Factset_spyderbot',
  'FirecrawlAgent',
  'FriendlyCrawler',
  'GeistHaus-PageFetcher',
  'Gemini-Deep-Research',
  'Google-Agent',
  'Google-Extended',
  'Google-Firebase',
  'Google-Gemini-CLI',
  'GoogleAgent-Mariner',
  'GoogleAgent-URLContext',
  'GoogleOther',
  'GPTBot',
  'HenkBot',
  'iAskBot',
  'iaskspider',
  'ICC-Crawler',
  'ImagesiftBot',
  'imageSpider',
  'img2dataset',
  'ISSCyberRiskCrawler',
  'kagi-fetcher',
  'Kangaroo Bot',
  'Kimi-Agent',
  'Kimi-SearchBot',
  'Kimi-User',
  'KimiBot',
  'KlaviyoAIBot',
  'KunatoCrawler',
  'laion-huggingface-processor',
  'LAIONDownloader',
  'LinerBot',
  'Linguee Bot',
  'LinkupBot',
  'Manus-User',
  'meta-externalagent',
  'meta-externalfetcher',
  'meta-webindexer',
  'MistralAI-Index',
  'MistralAI-Training',
  'MistralAI-User',
  'Mozilla-Tabstack',
  'MyCentralAIScraperBot',
  'NagetBot',
  'netEstate Imprint Crawler',
  'NotebookLM',
  'OAI-AdsBot',
  'OAI-SearchBot',
  'omgili',
  'PanguBot',
  'Panscient',
  'Perplexity-User',
  'PerplexityBot',
  'PetalBot',
  'PhindBot',
  'Poggio-Citations',
  'Poseidon Research Crawler',
  'QualifiedBot',
  'Querit-SearchBot',
  'QueritBot',
  'QuillBot',
  'QwenBot',
  'Reflectionbot',
  'SBIntuitionsBot',
  'SemrushBot-OCOB',
  'SemrushBot-SWA',
  'ShapBot',
  'Sidetrade indexer bot',
  'TavilyBot',
  'TerraCotta',
  'TikTokSpider',
  'Timpibot',
  'TongyiBot',
  'TwinAgent',
  'VelenPublicWebCrawler',
  'WARDBot',
  'Webzio-Extended',
  'wpbot',
  'WRTNBot',
  'YandexAdditional',
  'YiyanBot',
  'YouBot',
  'ZanistaBot',
];

const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');

export const AI_BOT_PATTERN = new RegExp(AI_BOT_TOKENS.map(escape).join('|'), 'i');
